-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.api_usage_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  job_id text,
  check_id text,
  api_provider text NOT NULL CHECK (api_provider = ANY (ARRAY['gemini'::text, 'openai'::text, 'vision'::text, 'numarkdown'::text])),
  api_model text,
  api_endpoint text,
  prompt_tokens integer DEFAULT 0,
  completion_tokens integer DEFAULT 0,
  total_tokens integer DEFAULT 0,
  cost_usd numeric DEFAULT 0,
  cost_input_usd numeric DEFAULT 0,
  cost_output_usd numeric DEFAULT 0,
  processing_time_ms integer,
  request_metadata jsonb DEFAULT '{}'::jsonb,
  response_metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT api_usage_logs_pkey PRIMARY KEY (id),
  CONSTRAINT api_usage_logs_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT api_usage_logs_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.check_jobs(job_id)
);
CREATE TABLE public.app_settings (
  id integer NOT NULL DEFAULT 1 CHECK (id = 1),
  gemini_api_key text,
  qbo_connected boolean DEFAULT false,
  qbo_company_id text,
  qbo_access_token text,
  qbo_refresh_token text,
  qbo_token_expires_at timestamp without time zone,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  tenant_id uuid,
  CONSTRAINT app_settings_pkey PRIMARY KEY (id),
  CONSTRAINT app_settings_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  tenant_id uuid NOT NULL,
  check_id uuid,
  user_id uuid,
  action text NOT NULL,
  entity_type text NOT NULL,
  entity_id uuid,
  old_values jsonb,
  new_values jsonb,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT audit_logs_check_id_fkey FOREIGN KEY (check_id) REFERENCES public.checks(id),
  CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.check_jobs (
  id integer NOT NULL DEFAULT nextval('check_jobs_id_seq'::regclass),
  job_id text NOT NULL UNIQUE,
  status text NOT NULL,
  pdf_name text NOT NULL,
  pdf_url text,
  file_size integer,
  doc_format text,
  total_pages integer DEFAULT 0,
  total_checks integer DEFAULT 0,
  checks_data jsonb,
  error_message text,
  created_at timestamp without time zone DEFAULT now(),
  completed_at timestamp without time zone,
  updated_at timestamp without time zone DEFAULT now(),
  tenant_id uuid,
  total_api_cost_usd numeric DEFAULT 0,
  total_tokens integer DEFAULT 0,
  api_usage_summary jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT check_jobs_pkey PRIMARY KEY (id),
  CONSTRAINT check_jobs_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.checks (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  tenant_id uuid NOT NULL,
  user_id uuid,
  file_url text NOT NULL,
  file_type text NOT NULL,
  file_size integer,
  check_number text,
  check_number_confidence numeric,
  check_number_source text CHECK (check_number_source = ANY (ARRAY['ocr'::text, 'ai'::text, 'hybrid'::text, 'manual'::text])),
  payee text,
  payee_confidence numeric,
  payee_source text CHECK (payee_source = ANY (ARRAY['ocr'::text, 'ai'::text, 'hybrid'::text, 'manual'::text])),
  amount numeric,
  amount_confidence numeric,
  amount_source text CHECK (amount_source = ANY (ARRAY['ocr'::text, 'ai'::text, 'hybrid'::text, 'manual'::text])),
  check_date date,
  check_date_confidence numeric,
  check_date_source text CHECK (check_date_source = ANY (ARRAY['ocr'::text, 'ai'::text, 'hybrid'::text, 'manual'::text])),
  bank_name text,
  bank_name_confidence numeric,
  bank_name_source text CHECK (bank_name_source = ANY (ARRAY['ocr'::text, 'ai'::text, 'hybrid'::text, 'manual'::text])),
  routing_number text,
  account_number text,
  memo text,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'processing'::text, 'pending_review'::text, 'approved'::text, 'rejected'::text, 'exported'::text, 'error'::text])),
  confidence_summary numeric,
  processing_method text CHECK (processing_method = ANY (ARRAY['ocr'::text, 'ai'::text, 'hybrid'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  processed_at timestamp with time zone,
  approved_at timestamp with time zone,
  exported_at timestamp with time zone,
  realm_id text,
  CONSTRAINT checks_pkey PRIMARY KEY (id),
  CONSTRAINT checks_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT checks_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.export_history (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  tenant_id uuid NOT NULL,
  user_id uuid,
  export_type text NOT NULL CHECK (export_type = ANY (ARRAY['quickbooks'::text, 'csv'::text, 'json'::text])),
  check_ids ARRAY NOT NULL,
  status text NOT NULL CHECK (status = ANY (ARRAY['pending'::text, 'in_progress'::text, 'completed'::text, 'failed'::text])),
  file_url text,
  error_message text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  CONSTRAINT export_history_pkey PRIMARY KEY (id),
  CONSTRAINT export_history_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT export_history_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.integrations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  provider text NOT NULL,
  realm_id text,
  access_token text,
  refresh_token text,
  expires_at timestamp with time zone,
  api_keys jsonb DEFAULT '{}'::jsonb,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  qb_client_id text,
  qb_client_secret text,
  qb_redirect_uri text,
  gemini_api_key text,
  tenant_id uuid,
  company_name text,
  CONSTRAINT integrations_pkey PRIMARY KEY (id),
  CONSTRAINT integrations_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.match_audit_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  match_id uuid NOT NULL,
  user_id uuid,
  action text NOT NULL,
  old_status text,
  new_status text,
  details jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT match_audit_log_pkey PRIMARY KEY (id),
  CONSTRAINT match_audit_log_match_id_fkey FOREIGN KEY (match_id) REFERENCES public.matches(id),
  CONSTRAINT match_audit_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.matches (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  user_id uuid,
  realm_id text NOT NULL,
  check_id uuid NOT NULL UNIQUE,
  qb_txn_id uuid,
  confidence_score numeric DEFAULT 0,
  confidence_reasons jsonb,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'matched'::text, 'approved'::text, 'flagged'::text, 'discrepancy'::text, 'unmatched'::text, 'rejected'::text])),
  discrepancy_amount numeric,
  discrepancy_type text,
  discrepancy_notes text,
  resolution text,
  resolution_notes text,
  resolved_by uuid,
  resolved_at timestamp with time zone,
  approved_by uuid,
  approved_at timestamp with time zone,
  notes text,
  flagged_reason text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT matches_pkey PRIMARY KEY (id),
  CONSTRAINT matches_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT matches_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT matches_check_id_fkey FOREIGN KEY (check_id) REFERENCES public.checks(id),
  CONSTRAINT matches_qb_txn_id_fkey FOREIGN KEY (qb_txn_id) REFERENCES public.qb_transactions(id),
  CONSTRAINT matches_resolved_by_fkey FOREIGN KEY (resolved_by) REFERENCES auth.users(id),
  CONSTRAINT matches_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES auth.users(id)
);
CREATE TABLE public.processing_stages (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  check_id uuid NOT NULL,
  stage_name text NOT NULL CHECK (stage_name = ANY (ARRAY['upload'::text, 'preprocessing'::text, 'segmentation'::text, 'ocr'::text, 'ai_extraction'::text, 'hybrid_selection'::text, 'validation'::text, 'review'::text, 'approval'::text, 'export'::text])),
  status text NOT NULL CHECK (status = ANY (ARRAY['pending'::text, 'in_progress'::text, 'completed'::text, 'failed'::text, 'skipped'::text])),
  progress numeric DEFAULT 0,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  error_message text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  tenant_id uuid,
  CONSTRAINT processing_stages_pkey PRIMARY KEY (id),
  CONSTRAINT processing_stages_check_id_fkey FOREIGN KEY (check_id) REFERENCES public.checks(id),
  CONSTRAINT processing_stages_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.qb_connections (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  user_id uuid,
  realm_id text NOT NULL,
  company_name text,
  company_logo_url text,
  access_token text NOT NULL,
  refresh_token text NOT NULL,
  token_expires_at timestamp with time zone NOT NULL,
  is_active boolean DEFAULT false,
  connected_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT qb_connections_pkey PRIMARY KEY (id),
  CONSTRAINT qb_connections_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT qb_connections_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.qb_entries (
  id text NOT NULL,
  qb_type text NOT NULL,
  qb_source text NOT NULL,
  check_number text DEFAULT ''::text,
  date text DEFAULT ''::text,
  amount text DEFAULT '0'::text,
  payee text DEFAULT ''::text,
  account text DEFAULT ''::text,
  memo text DEFAULT ''::text,
  raw_data jsonb,
  synced_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  tenant_id uuid,
  intuit_id text,
  CONSTRAINT qb_entries_pkey PRIMARY KEY (id),
  CONSTRAINT qb_entries_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.qb_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  user_id uuid,
  realm_id text NOT NULL,
  txn_id text NOT NULL,
  txn_type text,
  txn_date date,
  payee text,
  payee_id text,
  amount numeric,
  memo text,
  account text,
  doc_number text,
  synced_at timestamp with time zone DEFAULT now(),
  qb_source text,
  CONSTRAINT qb_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT qb_transactions_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT qb_transactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.qbo_connections (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  tenant_id uuid NOT NULL,
  realm_id text NOT NULL,
  access_token text NOT NULL,
  refresh_token text NOT NULL,
  token_expires_at timestamp with time zone NOT NULL,
  company_name text,
  is_active boolean DEFAULT true,
  last_sync_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT qbo_connections_pkey PRIMARY KEY (id),
  CONSTRAINT qbo_connections_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.quickbooks_entries (
  id integer NOT NULL DEFAULT nextval('quickbooks_entries_id_seq'::regclass),
  check_number text NOT NULL,
  date text NOT NULL,
  amount text NOT NULL,
  payee text NOT NULL,
  account text DEFAULT 'Checking'::text,
  memo text,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  tenant_id uuid,
  CONSTRAINT quickbooks_entries_pkey PRIMARY KEY (id),
  CONSTRAINT quickbooks_entries_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.tenants (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  settings jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  plan text NOT NULL DEFAULT 'free'::text CHECK (plan = ANY (ARRAY['free'::text, 'starter'::text, 'professional'::text, 'enterprise'::text, 'pro'::text])),
  CONSTRAINT tenants_pkey PRIMARY KEY (id)
);
CREATE TABLE public.user_profiles (
  id uuid NOT NULL,
  tenant_id uuid,
  email text NOT NULL,
  full_name text,
  role text NOT NULL DEFAULT 'member'::text CHECK (role = ANY (ARRAY['admin'::text, 'member'::text, 'viewer'::text])),
  settings jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT user_profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id),
  CONSTRAINT user_profiles_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id)
);
CREATE TABLE public.vouched_checks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  check_identifier text NOT NULL,
  check_number text,
  vouched_by uuid,
  vouched_at timestamp with time zone DEFAULT now(),
  reason text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT vouched_checks_pkey PRIMARY KEY (id),
  CONSTRAINT vouched_checks_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id),
  CONSTRAINT vouched_checks_vouched_by_fkey FOREIGN KEY (vouched_by) REFERENCES auth.users(id)
);